# Use JDK base image
FROM eclipse-temurin:22-jdk

# Set working directory
WORKDIR /app

# Copy the jar file
COPY StudentSurvey/target/StudentSurvey-0.0.1-SNAPSHOT.jar app.jar

# Expose the port Spring Boot runs on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
